name: Python CI

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install poetry
      - run: poetry install
      - run: pre-commit run --all-files